Push log to elk
iwayvietnam/zimbra-docker pull request #3
Opened 2021-07-20 03:10 UTC by hieunguyen23

Push log to ELK

2021-07-20 03:11 UTC, hieunguyen23 commented
Push log to ELK

2021-07-20 07:29 UTC, tuanta requested changes
Check these comments, improve your code then pull request back. Thanks.

2021-07-20 07:29 UTC, tuanta commented on zimbra_all/opt/push-logs-to-ELK/60-output.conf
> +*.*                         @logstash_ip:10514;json-template
This should be a specific IP (of Logstash), isn't it?
So how to pass that value to? (maybe through a parameter on "docker run"?)

2021-07-20 07:29 UTC, tuanta commented on zimbra_all/opt/build.sh
> +cp /opt/push-logs-to-ELK/* /etc/rsyslog.d/
How about clean up these files after one time setup?

2021-07-22 14:22 UTC, closed without merging

2021-07-22 14:28 UTC, tuanta commented
@hieunguyen23 không muốn merge nữa à :)